stages:
  - build
  - test
  - deploy

variables:
  POSTGRES_USER: bd11
  POSTGRES_PASSWORD: bd11

build_back:
  stage: build
  image: golang:latest
  services:
    - docker:dind
  script:
    - echo "Building back"
    - docker-compose build back

build_front:
  stage: build
  image: node:latest
  services:
    - docker:dind
  script:
    - echo "Building front"
    - docker-compose build front

test_back:
  stage: test
  image: golang:latest
  services:
    - docker:dind
  script:
    - echo "Running back tests"
    - docker-compose run back go test ./... -v

test_front:
  stage: test
  image: node:latest
  services:
    - docker:dind
  script:
    - echo "Running front tests"
    - docker-compose run front npm install
    - docker-compose run front npm run test

deploy:
  stage: deploy
  script:
    - echo "Deploying application"
    - docker-compose up -d
