stages:
  - build
  - test
  - deploy

variables:
  POSTGRES_USER: bd11
  POSTGRES_PASSWORD: bd11

before_script:
  - curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

build_back:
  stage: build
  image: docker/compose:1.29.2
  services:
    - docker:19.03.12-dind
  script:
    - echo "Building back"
    - docker-compose build back
    - docker-compose logs back 

test_back:
  stage: test
  image: docker/compose:1.29.2
  services:
    - docker:19.03.12-dind
  script:
    - echo "Running back tests"
    - docker-compose run back go test ./... -v

deploy:
  stage: deploy
  image: docker/compose:1.29.2
  services:
    - docker:19.03.12-dind
  script:
    - echo "Deploying application"
    - docker-compose up -d
