stages:
  - build
  - test
  - deploy

variables:
  POSTGRES_USER: bd11
  POSTGRES_PASSWORD: bd11

build_back:
  stage: build
  image: 
    - golang:latest
    - docker:stable-dind
  services:
    - docker:dind
  script:
    - echo "Building back"
    - docker build -t cnc_app:latest back
    - docker rm -f cnc_app || true
    - docker run -d --name cnc_app -p 8081:8080 --network cnc_app cnc_app:latest

test_back:
  stage: test
  image: 
    - golang:latest
    - docker:stable-dind
  services:
    - docker:dind
  script:
    - echo "Running back tests"
    - docker run cnc_app go test ./... -v

# deploy:
#   stage: deploy
#   image: docker:stable-dind
#   services:
#     - docker:dind
#   script:
#     - echo "Deploying application"
#     - docker compose up -d