stages:
  - build
  - test
  - deploy

variables:
  POSTGRES_USER: bd11
  POSTGRES_PASSWORD: bd11

build_back:
  stage: build
  image: docker:stable-dind
  services:
    - docker:dind
  script:
    - echo "Building back"
    - docker build -t cnc_app_back:latest -f back/Dockerfile back

test_back:
  stage: test
  image: docker:stable-dind
  services:
    - docker:dind
  script:
    - echo "Running back tests"
    - docker run --rm cnc_app_back go test ./... -v

deploy:
  stage: deploy
  image: docker:stable-dind
  services:
    - docker:dind
  script:
    - echo "Installing Docker Compose"
    - apk add --no-cache py3-pip
    - pip3 install docker-compose
    - echo "Deploying application"
    - docker-compose up -d