stages:
  - build
  - test
  - deploy

variables:
  POSTGRES_USER: bd11
  POSTGRES_PASSWORD: bd11

build_back:
  stage: build
  image: docker:stable-dind
  services:
    - docker:dind
  script:
    - echo "Building back"
    - docker build -t cnc_app_back:latest -f back/Dockerfile back

test_back:
  stage: test
  image: docker:stable-dind
  services:
    - docker:dind
  script:
    - echo "Running back tests"
    - docker run --rm cnc_app_back go test ./... -v

deploy:
  stage: deploy
  image: docker:stable-dind
  services:
    - docker:dind
  script:
    - echo "Installing Docker Compose"
    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    - echo "Deploying application"
    - docker-compose up -d