stages:
  - build
  - test
  - deploy

variables:
  POSTGRES_USER: bd11
  POSTGRES_PASSWORD: bd11

build_back:
  stage: build
  image: golang:latest
  script:
    - echo "Building back"
    - docker build -t myapp:latest back

test_back:
  stage: test
  image: golang:latest
  script:
    - echo "Running back tests"
    - docker run myapp go test ./... -v

deploy:
  stage: deploy
  image: docker:stable-dind
  services:
    - docker:dind
  script:
    - echo "Deploying application"
    - docker-compose up -d