stages:
  - build
  - test

variables:
  POSTGRES_USER: bd11
  POSTGRES_PASSWORD: bd11

build_back:
  stage: build
  image: docker:stable-dind
  services:
    - docker:dind
  script:
    - echo "Building back"
    - docker build -t cnc_app_back:latest -f back/Dockerfile back
    - docker rm -f cnc_app_back || true
    - docker run -d --name cnc_app_back -p 8081:8080 --network cnc_app_cnc_app cnc_app_back:latest

test_back:
  stage: test
  image: docker:stable-dind
  services:
    - docker:dind
  script:
    - echo "Running back tests"
    - docker run cnc_app_back go test ./... -v