version: '3.8'

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
    command: go run main.go

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    command: npm run dev

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: